# [Copyright]
# SmartPath v1.0
# Copyright 2014-2015 Mountain Pass Solutions, Inc.
# This unpublished material is proprietary to Mountain Pass Solutions, Inc.
# [End Copyright]

enter_serv_rank = {
	"code": "enter_serv_rank",
	"comment":"",
	"descr": "Enter Service & Rank",
	"header": "Enter Service & Rank",
	"componentType": "Task",
	"affordanceType":"Item",
	"optional": False,
	"enabled": True,
	"accessPermissions": ["dept_task"],
	"viewPermissions": ["dept_task","mss_task","ofa_task"],
	"blockers": [],
	"containers": [],
	"statusMsg": "",
	"successMsg":"Service & Rank was saved",
	"className": "ServiceAndRank",
	"config": {
		"template":"serv_rank_template.html",
		"image":"logoUMHS.png",
		"membershipCategories":[{"code":"AS","descr":"Active Staff","subcategories":[]},
		                       {"code":"CS","descr":"Courtesy Staff","subcategories":[{"code":"CSWA","descr":"Courtesy Staff - With Admitting Privileges"},
		                                                                               {"code":"CSWOA","descr":"Courtesy Staff - Without Admitting Privileges"},
		                                                                               {"code":"CSEUM","descr":"Courtesy Staff - Employed by U of M - With Privileges"},
		                                                                              {"code":"CSEUMWOP","descr":"Courtesy Staff - Employed by U of M - Without Privileges"}]},
		                       {"code":"HS","descr":"Honorary Staff","subcategories":[{"code":"HSWA","descr":"Honorary Staff - With Admitting Privileges"},
		                                                                               {"code":"HSWOA","descr":"Honorary Staff - Without Admitting Privileges"},]},
		                       {"code":"VS","descr":"Visiting Staff","subcategories":[{"code":"VSWA","descr":"Visiting Staff - With Admitting Privileges"},
		                                                                               {"code":"VSWOA","descr":"Visiting Staff - Without Admitting Privileges"}]},
		                    ],
		"activityLog": {
			"enabled": True,
			"activityLogText": "Enter Service & Rank",
		},
			"prompts": [
			{
				"code": "building_descr",
				"label": "Building",
				"enabled": True,
				"required": True,
				"data_type": "list",
			},
			{
				"code": "room",
				"label": "Room",
				"enabled": True,
				"required": False,
				"data_type": "string",
			},
			{
				"code": "spc",
				"label": "SPC",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "floor",
				"label": "Floor",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "reception",
				"label": "Reception",
				"enabled": True,
				"required": False,
				"data_type": "string",
			},
			{
				"code": "address_lines",
				"label": "Address",
				"enabled": True,
				"required": True,
				"data_type": "repeatingtext",
			},
			{
				"code": "city",
				"label": "City",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "state",
				"label": "State",
				"enabled": True,
				"required": False,
				"data_type": "list",
			},
			{
				"code": "country",
				"label": "Country",
				"enabled": True,
				"required": True,
				"data_type": "list",
			},
			{
				"code": "postal",
				"label": "Postal",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "phone",
				"label": "Phone",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "fax",
				"label": "Fax",
				"enabled": True,
				"required": False,
				"data_type": "string",
			},
			{
				"code": "email",
				"label": "Email",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
			{
				"code": "membership_category",
				"label": "Membership Category",
				"enabled": True,
				"required": True,
				"data_type": "string",
			},
		],
	},
}
