#!/bin/bash
# description: MPS Platform Start, Primary Environment
# processname: mps
# chkconfig: - 89 11
CAR_HOME=/home/mpsadmin/car

case $1 in
start)
/bin/su mpsadmin -c 'python /home/mpsadmin/car/commands/skynyrd.py --dst /usr/local/mps'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSAuthSvc.py -e staging --file config/staging/MPSAuthSvc/config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSAdmin.py -e staging --file config/staging/MPSAdmin/config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSCV.py -e staging --file config/staging/MPSCV/config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSCV.py -e staging --file config/staging/MPSCV/config_a.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSAppt.py -e staging --file config/staging/MPSAppt/config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSAppt.py -e staging --file config/staging/MPSAppt/config_a.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/car/MPSLogin.py -e staging --file config/staging/MPSLogin/config.json &'
;;
esac
exit 0
