#!/bin/bash
# description: MPS Platform Start, Alternate Environment 1
# processname: mps1
# chkconfig: - 89 11
CAR_HOME=/home/mpsadmin/alt1/car

case $1 in
start)
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/commands/skynyrd.py --dst /usr/local/mps1'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSAuthSvc.py -e staging --file config/staging/MPSAuthSvc/alt1_config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSAdmin.py -e staging --file config/staging/MPSAdmin/alt1_config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSCV.py -e staging --file config/staging/MPSCV/alt1_config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSCV.py -e staging --file config/staging/MPSCV/alt1_config_a.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSAppt.py -e staging --file config/staging/MPSAppt/alt1_config.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSAppt.py -e staging --file config/staging/MPSAppt/alt1_config_a.json &'
/bin/su mpsadmin -c 'python /home/mpsadmin/alt1/car/MPSLogin.py -e staging --file config/staging/MPSLogin/alt1_config.json &'
;;
esac
exit 0
