#!/bin/bash
#
# Supervisor is a client/server system that allows its users to monitor and control a
# number of processes on UNIX-like operating systems. We use it to start the shibboleth
# shibauthorizer and shibresponder apps.
#
# description: Supervisor Server
# processname: supervisord
# chkconfig: - 64 36

# Source init functions
. /etc/rc.d/init.d/functions

prog="supervisord"

prefix="/usr"
exec_prefix="${prefix}"
prog_bin="${exec_prefix}/bin/supervisord"
PIDFILE="/tmp/$prog.pid"

start()
{
       echo -n $"Starting $prog: "
       daemon $prog_bin --pidfile $PIDFILE --configuration=/etc/supervisord.conf
       sleep 2
       [ -f $PIDFILE ] && success $"$prog startup" || failure $"$prog startup"
       retval=$?
       echo
       [ $retval -eq 0 ] && [ -f $PIDFILE ]
       return $retval
}

stop()
{
       echo -n $"Shutting down $prog: "
       [ -f $PIDFILE ] && killproc $prog || success $"$prog shutdown"
       echo
}

case "$1" in

 start)
   start
 ;;

 stop)
   stop
 ;;

 status)
       status $prog
 ;;

 restart)
   stop
   start
 ;;

 *)
   echo "Usage: $0 {start|stop|restart|status}"
 ;;

esac
exit 0

