# [Copyright]
# SmartPath v1.0
# Copyright 2014-2015 Mountain Pass Solutions, Inc.
# This unpublished material is proprietary to Mountain Pass Solutions, Inc.
# [End Copyright]

overrides=[{'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'ClinicalClinicalInstructor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 1, 'min': 0}},
  'enabled': True,
  'titleCode': 'ClinicalClinicalAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ClinicalClinicalAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ClinicalClinicalProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'ClinicalLecturerClinicalLecturer(NonGME)',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'ClinicalLecturerClinicalLecturer',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'InstructionalAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'InstructionalAssociateProfessorwithoutTenure',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'InstructionalAssociateProfessorwithTenure',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'InstructionalProfessorwithoutTenure',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'InstructionalProfessorwithTenure',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'LeoLecturerLEOLecturerI',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'LeoLecturerLEOLecturerII',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'LeoLecturerLEOLecturerIII',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'LeoLecturerLEOLecturerIV',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'ResearchResearchInvestigator',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchAssistantResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchResearchAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchAssociateResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchResearchAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'ResearchResearchProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalAdjunctPhysicianInstructor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalAdjunctClinicalInstructor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalClinicalAssistantProfessorEmeritus/A',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalVisitingClinicalAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 1, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalClinicalAdjunctClinicalAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalClinicalAssociateProfessorEmeritus',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalClinicalAdjunctClinicalAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalClinicalClinicalProfessorEmeritus/A',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalClinicalAdjunctClinicalProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalAdjunctInstructor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalVisitingInstructor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalAssistantProfessorEmeritus/A',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalInstructionalAdjunctAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalVisitingAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalInstructionalAdjunctAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalAssociateProfessorEmeritus/a',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalInstructionalAdjunctProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalInstructionalProfessorEmeritus/a',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalLecturerVisitingClinicalLecturer',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalLecturerVisitingLecturer',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalLecturerAdjunctClinicalAssociate',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalLecturerAdjunctClinicalLecturer',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalLecturerAdjunctLecturer',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchAdjunctResearchInvestigator',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctAssistantResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchVisitingAssistantResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctResearchAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchVisitingResearchAssistantProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctAssociateResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchVisitingAssociateResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctResearchAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchVisitingResearchAssociateProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchResearchAssociateProfessorEmeritus/A',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctResearchScientist',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'config': {'config': {'max': 5, 'min': 0}},
  'enabled': True,
  'titleCode': 'SupplementalResearchAdjunctResearchProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchVisitingResearchProfessor',
  'workflowCode': 'umms_promote_workflow'},
 {'componentCode': u'recent_sig_pubs',
  'enabled': False,
  'titleCode': 'SupplementalResearchResearchProfessorEmeritus/A',
  'workflowCode': 'umms_promote_workflow'}]
