# [Copyright]
# SmartPath v1.0
# Copyright 2014-2015 Mountain Pass Solutions, Inc.
# This unpublished material is proprietary to Mountain Pass Solutions, Inc.
# [End Copyright]

overrides=[{'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ClinicalLecturerClinicalLecturer(NonGME)',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ClinicalLecturerClinicalLecturer',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'LeoLecturerLEOLecturerI',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'LeoLecturerLEOLecturerII',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'LeoLecturerLEOLecturerIII',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'LeoLecturerLEOLecturerIV',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchResearchInvestigator',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchAssistantResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchResearchAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchAssociateResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchResearchAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'ResearchResearchProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalAdjunctPhysicianInstructor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalAdjunctClinicalInstructor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalClinicalAssistantProfessorEmeritus/A',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalVisitingClinicalAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalAdjunctClinicalAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalClinicalAssociateProfessorEmeritus',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalAdjunctClinicalAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalClinicalProfessorEmeritus/A',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalClinicalAdjunctClinicalProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAdjunctInstructor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalVisitingInstructor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAssistantProfessorEmeritus/A',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAdjunctAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalVisitingAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAdjunctAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAssociateProfessorEmeritus/a',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalAdjunctProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalInstructionalProfessorEmeritus/a',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalLecturerVisitingClinicalLecturer',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalLecturerVisitingLecturer',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalLecturerAdjunctClinicalAssociate',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalLecturerAdjunctClinicalLecturer',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalLecturerAdjunctLecturer',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctResearchInvestigator',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctAssistantResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchVisitingAssistantResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctResearchAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchVisitingResearchAssistantProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctAssociateResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchVisitingAssociateResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctResearchAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchVisitingResearchAssociateProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchResearchAssociateProfessorEmeritus/A',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctResearchScientist',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchAdjunctResearchProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchVisitingResearchProfessor',
  'workflowCode': 'umms_appoint_workflow'},
 {'componentCode': u'rfp',
  'config': {u'draftActivityLog': {u'activityLogText': u'RFP saved as draft',
                                   u'enabled': True},
             u'draftEnabled': True,
             u'draftText': u'Save as Draft',
             u'omitCodes': '["RFP_Q00", "RFP_Q00_Y", "RFP_Q08", "RFP_Q08_Y", "RFP_Q09", "RFP_Q09_N", "RFP_Q11", "RFP_Q11_Y", "RFP_Q12", "RFP_Q12_Y"]',
             u'questionGroupCode': u'primaryRFP',
             u'savedSetsApplyActivityLog': {u'activityLogText': u'RFP saved set applied',
                                            u'enabled': False},
             u'savedSetsApplySuccessMsg': u'Saved set applied',
             u'savedSetsCreateActivityLog': {u'activityLogText': u'RFP saved set created',
                                             u'enabled': False},
             u'savedSetsCreateSuccessMsg': u'Saved set created',
             u'savedSetsDeleteActivityLog': {u'activityLogText': u'RFP saved set deleted',
                                             u'enabled': False},
             u'savedSetsDeleteSuccessMsg': u'Saved set deleted',
             u'savedSetsEnabled': True,
             u'submitActivityLog': {u'activityLogText': u'RFP saved',
                                    u'enabled': True},
             u'submitEnabled': True,
             u'submitText': u'Save'},
  'titleCode': 'SupplementalResearchResearchProfessorEmeritus/A',
  'workflowCode': 'umms_appoint_workflow'}]
