# [Copyright]
# SmartPath v1.0
# Copyright 2014-2015 Mountain Pass Solutions, Inc.
# This unpublished material is proprietary to Mountain Pass Solutions, Inc.
# [End Copyright]

promo_assist_dean_approval = {
	"code": "promo_assist_dean_approval",
	"descr": "Assistant Dean Approval",
	"header": "Assistant Dean Approval",
	"componentType": "Task",
	"affordanceType":"Item",
	"optional": False,
	"enabled": True,
	"logEnabled": True,
	"freezable": True,
	"accessPermissions": ["assist_dean_task","ofa_task"],
	"viewPermissions": ["assist_dean_task","ofa_task"],
	"blockers": ["approveOFA"],
	"statusMsg": "",
	"successMsgApprove":"Assistant Dean Appointment Approved",
	"successMsgDeny":"Assistant Dean Appointment Denied",
	"successMsgRevisions":"Assistant Dean Appointment Revisions Required",
	"className": "Approval",
	"config": {
		"approve": True,
		"approveDashboardEvents": [{
			"code":["advisoryapproved","ofapacketapproved"],
			"eventType":"remove",
		},{
			"code":"assistdeanapproved",
			"sortOrder":"r1",
			"eventDescription":"Assistant Dean Review Complete",
			"eventType":"create",
			"permission":["ofa_task"]
		},],
		"denyDashboardEvents": [{
			"code":["advisoryapproved","ofapacketapproved"],
			"eventType":"remove",
		},{
			"code":"ofapacketrevisions",
			"sortOrder":"r2",
			"eventDescription":"Packet Revisions Required",
			"eventType":"create",
			"permission":["ofa_task"]
		}],
		"approveText": "Approve",
		"approveStatusMsg": "Assistant Dean Review Complete",
		"approveFreeze": {
			"freezeJobAction": False,
			"freezeSelf": False,
			"freezeAllPredecessors": False,
			"freezeTasks": [],
			"unfreezeJobAction": False,
			"unfreezeSelf": False,
			"unfreezeAllPredecessors": False,
			"unfreezeTasks": [],
			"setJobActionRevisionsRequired": False,
			"clearJobActionRevisionsRequired": False,
			"clearSubmitStatus": "",
			"activityLogText": "Approved",
		},
		"deny": True,
		"confirmDeny":False,
		"denyText": "Revisions Required",
		"denyStatusMsg": "Assistant Dean Revisions Required",
		"denyFreeze": {
			"freezeJobAction": False,
			"freezeSelf": False,
			"freezeAllPredecessors": False,
			"freezeTasks": [],
			"unfreezeJobAction": False,
			"unfreezeSelf": False,
			"unfreezeAllPredecessors": False,
			"unfreezeTasks": ["approveOFA"],
			"setJobActionRevisionsRequired": True,
			"clearJobActionRevisionsRequired": False,
			"clearSubmitStatus": ["assist_dean_approval","approveOFA"],
			"activityLogText": "Assistant Dean Revisions Required",
		},
		"revisionsRequired": False,
		"revisionsRequiredText": "Revisions Required",
		"revisionsRequiredStatusMsg": "Revisions Required",
		"revisionsRequiredFreeze": {
			"freezeJobAction": False,
			"freezeSelf": False,
			"freezeAllPredecessors": False,
			"freezeTasks": [],
			"unfreezeJobAction": False,
			"unfreezeSelf": False,
			"unfreezeAllPredecessors": False,
			"unfreezeTasks": [],
			"unfreezeOptions": ["approveOFA"],
			"setJobActionRevisionsRequired": True,
			"clearJobActionRevisionsRequired": False,
			"clearSubmitStatus": "approveOFA",
			"activityLogText": "Revisions Required",
		},
		"activityLog": {
			"enabled": True,
			"activityLogText": "Packet Approved",
			"comments": [
				{
					"commentCode": "assistdeanpacketapprovalcomment",
					"commentLabel": "Comment",
					"accessPermissions": ["ofa_task","assist_dean_approval"],
					"viewPermissions": ["ofa_task","assist_dean_approval"],
				},
			],
		},
		"activityLogTaskCodes": ["assist_dean_approval"],
		"vote": False,
	},
}
