SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

-- people on the happy path
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (1,'','Avi','Drissman','','','trucker@wheelsahHummin.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (2,'','Wilhem','Sphinx','Jr.','','wilhelm@sphinx.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (3,'','William','Kahoney','Sr.','James','william@kahoney.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (4,'','Aunt','Bee','Sr.','','aunt@bee.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (5,'','Robert','Zimmerman','','Dylan','bob@dylan.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--positions
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (1,10,3,'9-00001',True,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (2,11,18,'10-00001',True,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (3,12,44,'10-00002',True,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (4,13,62,'10-00003',True,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (5,14,24,'10-00004',True,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (6,10,33,'9-00002',True,'2010-10-10','2010-10-10','eric');
--appointments
INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (1,null,10,1,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (2,null,11,2,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (3,null,12,3,'2010-10-10','2010-10-10',1,'2010-10-10','2010-10-10','eric');
INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (4,4,13,4,'2010-10-10','2010-10-10',1,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (5,5,14,5,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--job_actions
INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,job_action_type_id,current_status,workflow_id,workflow_json,complete,frozen,revisions_required,external_key,created,updated,completed,lastuser,cancelation_comment,cancelation_user,cancelation_date) VALUES (3,null,3,3,2,'',1,'','f','f','f','4e385b5aaebc4e5a951eb5b858d1c85d','2010-10-10 12:12:12.121212','2010-10-10 12:12:12.121212','','eric','','','');
INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,job_action_type_id,current_status,workflow_id,workflow_json,complete,frozen,revisions_required,external_key,created,updated,completed,lastuser,cancelation_comment,cancelation_user,cancelation_date) VALUES (4,4,4,4,2,'',1,'','f','f','f','81f6effd857744389444eb1a30668d20','2010-10-10 12:12:12.121212','2010-10-10 12:12:12.121212','','eric','','','');
--INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,current_status,workflow_id,workflow_json,complete,frozen,revisions_required,created,updated,completed,lastuser) VALUES (5,5,5,5,'',3,'','f','f','f','2010-10-10','2010-10-10','','eric');

-- a Vacant Secondary position
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (7,10,33,'9-00009',False,'2010-10-10','2010-10-10','jimbo');

-- people on the not so happy path
-- Norman Odam has 2 job actions - new appointment and credentialing id 100
INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (100,'','Norman','Odam','','Carl','theledge@stardustcowboy.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--position for Norman Odam id 7
INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (100,10,52,'9-00003',True,'2010-10-10','2010-10-10','eric');
--appointment - Norman Odam rows 6&7
INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (100,null,15,100,'2010-10-10','2010-10-10',1,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (101,100,15,100,'2010-10-10','2010-10-10',1,'2010-10-10','2010-10-10','eric');
--job action Norman Odam
INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,job_action_type_id,current_status,workflow_id,workflow_json,complete,frozen,revisions_required,external_key,created,updated,completed,lastuser,cancelation_comment,cancelation_user,cancelation_date) VALUES (100,null,100,100,2,'',1,'','f','f','f','2123d39833734800925bf20537dff909','2010-10-10 12:12:12.121212','2010-10-10 12:12:12.121212','','eric','','','');


-- person ids 200 & 201 - one position, two people, no job actions
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (200,'duo','Frederick','Duo','','Michael','frederick@duo.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (201,'couple','Fernando','Coupler','','Butch','coupler@two.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--position for double fill with no actions id 8
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (200,10,35,'9-00004',True,'2010-10-10','2010-10-10','eric');
--double fill - one appointment row for each person - no job actions rows 8&9
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (200,200,15,200,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (201,201,16,200,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--no job actions for first double fill example


-- person id 300 - one position, two people, 2nd unidentified with action started
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (300,'imaalone','Ima','Alone','','Betty','betty@imaalone.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
-- id 9 double fill person in position with 2nd person unidentified
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (300,10,17,'9-00005',True,'2010-10-10','2010-10-10','eric');
--double fill - one appointment row for each person - one job action rows 10&11
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (300,300,15,300,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (301,null,16,300,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--one job action for unknown person that will be appointed to secondary
--INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,current_status,workflow_id,created,updated,completed,lastuser) VALUES (300,null,300,301,'',1,'2010-10-10','2010-10-10','','eric');


-- person id 400s - one position, two people, 2nd identified with action started
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (400,'andy','Andy','Griffith','','','andy@mayberry.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (401,'barney','Barney','Fife','','','barney@mayberry.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
-- id 10 double fill person in position with 2nd person unidentified
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (400,10,64,'9-00006',True,'2010-10-10','2010-10-10','eric');
--double fill - one appointment row for each person - one job action rows 10&11
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (400,400,15,400,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (401,401,16,400,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--one job action for unknown person that will be appointed to secondary
--INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,current_status,workflow_id,created,updated,completed,lastuser) VALUES (400,401,400,401,'',1,'2010-10-10','2010-10-10','','eric');


-- person id 500s - one primary position, some number of secondary, job action on one of the secondaries.
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (500,'bee','Aunt','Bee','','','bee@mayberry.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','eric');
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (500,10,69,'9-00007',True,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (501,11,42,'10-00009',False,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (502,20,6,'20-00010',False,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (500,500,15,500,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (501,500,15,501,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (502,500,15,502,'2010-10-10','2010-10-10',2,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (503,500,16,501,'2010-10-10','2010-10-10',1,'2010-10-10','2010-10-10','eric');
--INSERT INTO wf_job_action (id,person_id,position_id,appointment_id,current_status,workflow_id,workflow_json,complete,frozen,revisions_required,created,updated,completed,lastuser) VALUES (500,500,501,503,'Secondary Promotion',1,'','f','f','f','2010-10-10','2010-10-10','','eric');
--
--
---- person id 600s - person in a secondary position that has no primary appointment
--INSERT INTO wf_person (id,username,first_name,last_name,suffix,middle_name,email,employee_nbr,created,updated,lastuser) VALUES (600,'kirk','James','Kirk','','Tiberius','jkirk@enterprise.com','','2010-01-01 12:12:12','2010-01-01 12:12:12','spock');
--INSERT INTO wf_position (id,department_id,title_id,pcn,is_primary,created,updated,lastuser) VALUES (601,11,42,'10-00600',False,'2010-10-10','2010-10-10','spock');
--INSERT INTO wf_appointment (id,person_id,title_id,position_id,start_date,end_date,appointment_status_id,created,updated,lastuser) VALUES (602,600,11,601,'2010-10-10','2010-10-10',3,'2010-10-10','2010-10-10','spock');
--

UPDATE wf_pcn SET seq = 100;

--username & department join
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','eric',18);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','greg',31);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','chris',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','chris',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','rider',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','rider',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','rider',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','rider',14);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','kleahy',74);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dkomorow',74);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','gawd',74);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','dean',74);

INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','renee',74);


INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',1);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',2);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',3);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',4);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',5);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',6);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',7);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',8);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',9);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',10);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',11);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',12);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',13);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',14);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',15);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',16);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',17);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',18);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',19);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',20);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',21);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',22);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',23);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',24);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',25);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',26);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',27);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',28);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',29);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',30);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',31);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',32);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',33);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',34);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',35);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',36);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',37);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',38);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',39);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',40);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',41);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',42);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',43);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',44);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',45);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',46);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',47);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',48);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',49);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',50);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',51);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',52);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',53);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',54);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',55);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',56);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',57);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',58);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',59);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',60);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',61);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',62);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',63);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',64);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',65);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',66);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',67);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',68);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',69);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',70);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',71);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',72);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',73);
INSERT INTO wf_username_department (community,username,department_id) VALUES ('default','ellen',74);


ALTER SEQUENCE wf_person_id_seq RESTART WITH 10000;
ALTER SEQUENCE wf_position_id_seq RESTART WITH 10000;
ALTER SEQUENCE wf_appointment_id_seq RESTART WITH 10000;
ALTER SEQUENCE wf_job_action_id_seq RESTART WITH 10000;
